spring:
  application:
    name: dentoice-service
  datasource:
    url: jdbc:postgresql://${db.host:172.17.0.2}:5432/postgres
    username: postgres
    password: ${db.password:installed}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: com.mariakamachine.dentoice.config.postgres.JsonbPostgresSqlDialect
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    enabled: true
    drop-first: true
    user: postgres

server:
  port: 9876

invoice:
  mwstPercentage: 7.00
  skontoPercentage: 3.00
  xsdVersion: 4.0
  softwareVersion: 0.0.1
