spring:
  application:
    name: dentoice-service
  datasource:
    url: jdbc:postgresql://${db.host:172.17.0.2}:5432/dentoice
    username: dentoice
    password: ${general.password:F3s2pJ84Dn}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: com.mariakamachine.dentoice.config.postgres.JsonbPostgresSqlDialect
        jdbc:
          lob:
            non_contextual_creation: true
  jmx:
    enabled: false
  liquibase:
    enabled: false
    drop-first: false
    user: dentoice
  mail:
    host: smtp.gmail.com
    port: 587
    username: dentaltechnik.baumann
    password: ${general.password:F3s2pJ84Dn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 9876

invoice:
  xsdVersion: 4.0
  softwareVersion: 0.0.1
