spring:
  application:
    name: dentoice-service
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:2345/dentoice
    username: dentoice
    password: ${general.password:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: com.mariakamachine.dentoice.config.postgres.JsonbPostgresSqlDialect
        jdbc:
          lob:
            non_contextual_creation: true
  jmx:
    enabled: false
  liquibase:
    enabled: true
    drop-first: true
    user: dentoice
  mail:
    host: smtp.gmail.com
    port: 587
    username: dentaltechnik.baumann
    password: ${general.password:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 9876

invoice:
  xsdVersion: 4.0
  softwareVersion: 0.0.1
